### ISSUE TITLE
Ruby capstone project

### ISSUE THREAD

**Issue by mariegrace31** [mahdinoori2000/ruby-group-capstone#30]
- Here is [ the link](https://github.com/mahdinoori2000/ruby-group-capstone/projects/1) to our Github project.
 - In our team, we are four people: @ctokoli, @kerlos-bahaa, @mahdinoori2000  and @mariegrace31 
 - The task for:
     - Team member 1 was assigned to @ctokoli 
     - Team member 2 was assigned to @mahdinoori2000 
     - Team member 3 was assigned to @kerlos-bahaa 
     - Team member 4 was assigned to @mariegrace31

**Comment by julie-ify** [comment]
Hi @mariegrace31, @ctokoli, @kerlos-bahaa and @mahdinoori2000,

## Highlights!
- Descriptive issue and tasks ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
